### ISSUE TITLE
css sourcemap이 파일을 가리키지 않음

### ISSUE THREAD

**Issue by yrnana** [eunvanz/react-awesome-ptr#3]
![image](https://user-images.githubusercontent.com/19503504/161881989-e9ca9b7e-6efe-4452-ad7e-238d3b3358cd.png)
![image](https://user-images.githubusercontent.com/19503504/161882079-daabfe2a-d5ef-4284-a63a-85fed334b2c7.png)
![image](https://user-images.githubusercontent.com/19503504/161882286-e734654d-2f26-4861-8442-0cd86043e1e2.png)

안녕하세요!
dist/폴더에 scss파일들이 없어서 워닝이 발생합니다

**Comment by eunvanz** [comment]
@yrnana 1.0.62 전에서 `*.scss` 파일들을 `dist` 폴더 내에 위치 시키는 방식으로 소스매핑이 되도록 수정했습니다. 확인 한번만 부탁드릴게요! 확인 후 클로즈 부탁드리겠습니다. 🙏

**Comment by yrnana** [comment]
@eunvanz nexus 캐시때문에 아직 설치가 안되네요!ㅠㅠ 확인하면 클로즈하겠습니다!

**Comment by yrnana** [comment]
nexus를 기다리기엔 시간이 오래걸릴 것 같아 별도 레포에서 테스트해봤는데 잘됩니다 감사합니다!
