### ISSUE TITLE
touchmove event에서 오류 발생

### ISSUE THREAD

**Issue by yrnana** [eunvanz/react-awesome-ptr#4]
![image](https://user-images.githubusercontent.com/19503504/161936650-22e0c1d1-c06d-47eb-bdf0-243ef3965b01.png)
![image](https://user-images.githubusercontent.com/19503504/161936705-48672d25-c5fe-4e98-bc90-aa1056d57e0e.png)
1.0.61 설치후 스크롤 시도시 위와 같은 오류가 발생합니다. (user-agent android)

https://www.uriports.com/blog/easy-fix-for-intervention-ignored-attempt-to-cancel-a-touchmove-event-with-cancelable-false/
```ts
if (event.cancelable) event.preventDefault();
```
구글링을 해보니 위와 같이 작성하라는 이야기가 있네요ㅎㅎ

**Comment by eunvanz** [comment]
@yrnana 1.0.63 버전에서 해결했습니다. 요것도 확인해보시고 클로즈 부탁드리겠습니다!

**Comment by yrnana** [comment]
아주 잘 됩니다 감사합니다!!
